-- ============================================
-- Seed de la carta — extraído de index.html
-- ============================================

insert into categorias (id, nombre, orden) values
  ('pizzas-novedades', 'Novedades de la Casa', 0),
  ('pizzas-clasicas', 'Pizzas Clásicas', 1),
  ('pizzas-especiales', 'Pizzas Especiales', 2),
  ('pasta', 'Pastas al Horno', 3),
  ('entrantes', 'Entrantes', 4),
  ('ensaladas', 'Ensaladas', 5),
  ('postres', 'Postres', 6),
  ('bebidas', 'Bebidas', 7),
  ('vinos', 'Vinos', 8)
on conflict (id) do update set nombre = excluded.nombre, orden = excluded.orden;

insert into platos (categoria_id, nombre, descripcion, precio, tag, tag_popular, orden) values
  ('pizzas-novedades', 'Watami', 'Tomate, mozzarella 100%, viruta de bonito, alga wakame, aguacate, atún fresco macerado con soja y salsa de mango, cebollino, stracciatella, mayonesa de kimchi y sésamo negro', 16.80, 'Última incorporación', true, 0),
  ('pizzas-novedades', 'Zucca', 'Calabaza, mozzarella 100%, setas, ricotta, guanciale y scamorza', 14.20, NULL, false, 10),
  ('pizzas-novedades', 'Botánico', 'Base de ricotta, mozzarella 100%, yema, setas, jamón serrano ibérico y queso de cabra curado de la zona', 15.80, 'De la casa', false, 20),
  ('pizzas-novedades', 'Ventresca', 'Base de tomate, mozzarella 100%, ventresca de atún, pimiento rojo, cebolla y queso de cabra madurado', 13.20, NULL, false, 30),
  ('pizzas-clasicas', 'Margarita', 'Base de tomate, mozzarella 100% y albahaca', 9.50, NULL, false, 0),
  ('pizzas-clasicas', 'Margarita Original', 'Base de tomate, mozzarella 100% de búffala, albahaca y aceite de oliva', 10.50, NULL, false, 10),
  ('pizzas-clasicas', 'Prosciutto', 'Base de tomate, mozzarella 100% y jamón york', 10.80, NULL, false, 20),
  ('pizzas-clasicas', 'Romana', 'Base de tomate, mozzarella 100%, champiñones y jamón york', 11.00, NULL, false, 30),
  ('pizzas-clasicas', 'Pepparoni', 'Base de tomate, mozzarella 100% y pepperoni', 10.80, 'Novedad', true, 40),
  ('pizzas-clasicas', 'Carbonara', 'Base de nata, mozzarella 100%, bacon, champiñones y cebolla', 12.20, NULL, false, 50),
  ('pizzas-clasicas', '4 Estaciones', 'Base de tomate, mozzarella 100%, jamón york, bacon, ventresca de atún y champiñones', 12.20, NULL, false, 60),
  ('pizzas-clasicas', '4 Quesos', 'Base de tomate, mozzarella 100%, gorgonzola, gouda y parmesano', 12.20, NULL, false, 70),
  ('pizzas-clasicas', 'Barbacoa', 'Base de salsa barbacoa, mozzarella 100%, carne de ternera picada, cebolla y bacon', 12.20, NULL, false, 80),
  ('pizzas-clasicas', 'Suiza', 'Base de tomate, mozzarella 100%, bacon, cebolla y gorgonzola', 12.20, NULL, false, 90),
  ('pizzas-clasicas', 'Hawaiana', 'Base de tomate, mozzarella 100%, jamón york, piña y doble de queso', 12.20, NULL, false, 100),
  ('pizzas-clasicas', 'Marinera', 'Base de tomate, mozzarella 100%, ventresca de atún, anchoas y aceitunas negras', 12.20, NULL, false, 110),
  ('pizzas-especiales', 'Barbacoa Cream', 'Base de salsa barbacoa cremosa, mozzarella 100%, cebolla, carne de ternera picada y bacon', 13.20, NULL, false, 0),
  ('pizzas-especiales', 'Carbonara Sweet', 'Base de nata, mozzarella 100%, bacon, champiñones y cebolla caramelizada', 13.20, NULL, false, 10),
  ('pizzas-especiales', 'Barbacoa Hot', 'Base de salsa barbacoa picante, mozzarella 100%, cebolla, carne de ternera picada, pepperoni y bacon', 13.20, NULL, false, 20),
  ('pizzas-especiales', '5 Quesos', 'Base de nata, mozzarella 100%, gouda, chédar, cabra y parmesano', 13.20, NULL, false, 30),
  ('pizzas-especiales', 'Vegetariana', 'Base de tomate, mozzarella 100%, espárragos, cebolla, champiñones, tomate natural en rodajas y berenjena', 12.80, NULL, false, 40),
  ('pizzas-especiales', 'Montesa', 'Base de tomate, mozzarella 100%, bacon, champiñones y queso de cabra', 12.80, NULL, false, 50),
  ('pizzas-especiales', 'César', 'Mozzarella 100%, rúcula, bacon, pollo crujiente y salsa césar', 13.20, NULL, false, 60),
  ('pizzas-especiales', 'Summer', 'Base de crema de queso, mozzarella 100%, aguacate, salmón ahumado, cebolla roja, sésamo, mostaza y miel', 14.50, NULL, false, 70),
  ('pizzas-especiales', 'María', 'Base de tomate, mozzarella 100%, ajo, rúcula, jamón serrano, parmesano DOP y aceite de oliva', 14.50, NULL, false, 80),
  ('pizzas-especiales', 'Panda Thai', 'Crema de queso, mozzarella 100%, pollo al curry, queso gouda, pimiento rojo y salsa thai agridulce', 13.20, NULL, false, 90),
  ('pizzas-especiales', '4 Quesos con Ajo Negro', 'Base de nata, mozzarella 100%, gorgonzola, queso manchego DOP, parmesano DOP y ajo negro', 14.50, NULL, false, 100),
  ('pizzas-especiales', 'Rústica', 'Crema de queso, mozzarella, queso de cabra, láminas de pera, cebolla caramelizada y albahaca', 14.50, NULL, false, 110),
  ('pizzas-especiales', 'Pastoral', 'Salsa de tomate, mozzarella 100%, espinacas frescas, láminas de manzana, queso de cabra y nueces', 14.20, NULL, false, 120),
  ('pizzas-especiales', 'Siciliana', 'Salsa de tomate, mortadela, mozzarella de búfala, rúcula, pesto de pistacho, lascas de parmesano DOP y burrata', 15.20, NULL, false, 130),
  ('pizzas-especiales', 'Burrata', 'Salsa de tomate, jamón serrano, rúcula, cherry deshidratado, lascas de parmesano DOP y burrata', 15.20, NULL, false, 140),
  ('pasta', 'Pasta Rellena de Carne', NULL, 11.80, NULL, false, 0),
  ('pasta', 'Pasta Verde Rellena de Espinacas y Requesón', NULL, 11.80, NULL, false, 10),
  ('pasta', 'Pasta Rellena de Gorgonzola', NULL, 11.80, NULL, false, 20),
  ('pasta', 'Pasta Rellena de Pera', NULL, 11.80, NULL, false, 30),
  ('pasta', 'Lasaña Boloñesa', NULL, 11.80, NULL, false, 40),
  ('pasta', 'Lasaña Vegetal', NULL, 11.80, NULL, false, 50),
  ('entrantes', 'Provolone', 'Provolone con tomate especiado al horno', 10.20, NULL, false, 0),
  ('entrantes', 'Pan de Pizza con Mantequilla', 'Pan de pizza con mantequilla de la casa', 7.50, NULL, false, 10),
  ('entrantes', 'Pan de Pizza con Paté', 'Pan de pizza con paté', 9.80, NULL, false, 20),
  ('ensaladas', 'Caprese', 'Tomate, mozzarella fresca de búffala, aceitunas negras, albahaca, sal y pimienta negra', 9.80, NULL, false, 0),
  ('ensaladas', 'De la Casa', 'Rúcula, canónigos, pollo crujiente, salsa de yogur, pasas, nueces, parmesano DOP y picatostes', 10.80, NULL, false, 10),
  ('ensaladas', 'César', 'Pollo crujiente, lechuga, tomate cherry, picatostes, bacon, parmesano DOP y salsa césar', 10.20, NULL, false, 20),
  ('ensaladas', 'Cabra', 'Brotes tiernos, bacon, tomate cherry, queso de cabra, salsa miel y mostaza, nueces, pasas y picatostes', 13.50, NULL, false, 30),
  ('ensaladas', 'Burrata', 'Espinacas baby, burrata, tomate seco en aceite, piñones, pesto de pistacho, picatostes, bacon y parmesano DOP', 13.80, NULL, false, 40),
  ('postres', 'Tiramisú', 'Tiramisú casero', 5.50, NULL, false, 0),
  ('postres', 'Tarta de Queso', 'Tarta de queso casera', 5.00, NULL, false, 10),
  ('postres', 'Pizza Dulce de Nutella y Lacasitos', 'Pizza dulce con Nutella y Lacasitos', 9.20, NULL, false, 20),
  ('postres', 'Pizza Dulce de Chocolate Blanco y Oreo', 'Pizza dulce de chocolate blanco y galletas Oreo', 9.20, NULL, false, 30),
  ('bebidas', 'Refrescos', 'Cola, Cola Zero, Cola Zero Zero, Fanta Naranja, Fanta Limón y Seven-Up', 2.50, NULL, false, 0),
  ('bebidas', 'Nestea', NULL, 2.80, NULL, false, 10),
  ('bebidas', 'Acuarius', 'Normal o Naranja', 2.80, NULL, false, 20),
  ('bebidas', 'Zumo', 'Piña o melocotón', 2.20, NULL, false, 30),
  ('bebidas', 'Agua 1/2 L', NULL, 1.60, NULL, false, 40),
  ('bebidas', 'Agua 1 L', NULL, 3.00, NULL, false, 50),
  ('bebidas', 'Agua con Gas', NULL, 2.30, NULL, false, 60),
  ('bebidas', 'Mosto', NULL, 2.30, NULL, false, 70),
  ('bebidas', 'Limonada', NULL, 3.00, NULL, false, 80),
  ('bebidas', 'Bitter Kas', NULL, 2.30, NULL, false, 90),
  ('bebidas', 'Tónica', NULL, 2.30, NULL, false, 100),
  ('bebidas', 'Tercio Estrella Galicia', NULL, 3.00, NULL, false, 110),
  ('bebidas', 'Estrella Galicia Sin Alcohol', NULL, 3.00, NULL, false, 120),
  ('bebidas', 'Radler', NULL, 3.00, NULL, false, 130),
  ('bebidas', 'Tinto de Verano', NULL, 2.50, NULL, false, 140),
  ('bebidas', 'Tercio 1925', NULL, 3.50, NULL, false, 150),
  ('bebidas', 'Tercio Red Vintage', NULL, 3.50, NULL, false, 160),
  ('bebidas', 'Tercio 1906', NULL, 3.50, NULL, false, 170),
  ('bebidas', 'Sidra Maeloc', 'Sabor pera, fresa o mora', 3.50, NULL, false, 180),
  ('vinos', 'Ribera del Duero — Protos', 'Copa · Botella 15 €', 3.10, NULL, false, 0),
  ('vinos', 'Ribera del Duero — Melior', 'Copa · Botella 15 €', 3.10, NULL, false, 10),
  ('vinos', 'Rioja — Ramón Bilbao', 'Copa · Botella 15 €', 3.10, NULL, false, 20),
  ('vinos', 'Verdejo — Protos', 'Copa · Botella 15 €', 3.00, NULL, false, 30),
  ('vinos', 'Espumoso Yllera 5.0', 'Botella (solo botella)', 14.00, NULL, false, 40);
